
CREATE OR REPLACE FORCE VIEW "PULSEUSER"."NOTIFICATION" ("ID", "TYPE", "CREATED_ON", "NAME", "TEAM_LEADER_ID", "IS_READ")
                                      AS
    SELECT "NOTIFICATION"."ID"        AS "ID",
      "NOTIFICATION"."TYPE"           AS "TYPE",
      "NOTIFICATION"."CREATED_ON"     AS "CREATED_ON",
      "NOTIFICATION"."NAME"           AS "NAME",
      "NOTIFICATION"."TEAM_LEADER_ID" AS "TEAM_LEADER_ID",
      "NOTIFICATION"."IS_READ"        AS "IS_READ"
    FROM "TBL_NOTIFICATION" "NOTIFICATION";

CREATE OR REPLACE FORCE VIEW "PULSEUSER"."LOB_CONFIGURATION_NOTIF" ("ID", "NAME", "TYPE", "MESSAGE", "CREATED_ON", "AGENT_ID", "LOB_CONFIGURATION_ID", "TEAM_LEADER_ID", "CMS_ENTRY_ID", "WORKED_ID", "IS_READ")
                                                     AS
  SELECT "NOTIFICATION"."ID"                         AS "ID",
    "NOTIFICATION"."NAME"                            AS "NAME",
    "NOTIFICATION"."TYPE"                            AS "TYPE",
    "LOB_CONFIGURATION_NOTIF"."MESSAGE"              AS "MESSAGE",
    "NOTIFICATION"."CREATED_ON"                      AS "CREATED_ON",
    "LOB_CONFIGURATION_NOTIF"."AGENT_ID"             AS "AGENT_ID",
    "LOB_CONFIGURATION_NOTIF"."LOB_CONFIGURATION_ID" AS "LOB_CONFIGURATION_ID",
    "NOTIFICATION"."TEAM_LEADER_ID"                  AS "TEAM_LEADER_ID",
    "LOB_CONFIGURATION_NOTIF"."CMS_ENTRY_ID"         AS "CMS_ENTRY_ID",
    "LOB_CONFIGURATION_NOTIF"."WORKED_ID"            AS "WORKED_ID",
    "NOTIFICATION"."IS_READ"                         AS "IS_READ"
  FROM "TBL_LOB_CONFIGURATION_NOTIF" "LOB_CONFIGURATION_NOTIF"
  JOIN "TBL_NOTIFICATION" "NOTIFICATION"
  ON "NOTIFICATION".Id = "LOB_CONFIGURATION_NOTIF".Id;



CREATE OR REPLACE FORCE VIEW "PULSEUSER"."DISCREPANCY_DETECTED_NOTIF" ("ID", "AUX_CODE_ENTRY_NAME", "NAME", "TYPE", "MESSAGE", "CREATED_ON", "LOB_CONFIGURATION_ID", "AGENT_ID", "TEAM_LEADER_ID", "TIMECARD_ACTIVITY_ID", "IS_READ")
                                                        AS
  SELECT "DISCREPANCY_DETECTED_NOTIF"."ID"              AS "ID",
    "DISCREPANCY_DETECTED_NOTIF"."AUX_CODE_ENTRY_NAME"  AS "AUX_CODE_ENTRY_NAME",
    "NOTIFICATION"."NAME"                               AS "NAME",
    "NOTIFICATION"."TYPE"                               AS "TYPE",
    "LOB_CONFIGURATION_NOTIF"."MESSAGE"                 AS "MESSAGE",
    "NOTIFICATION"."CREATED_ON"                         AS "CREATED_ON",
    "LOB_CONFIGURATION_NOTIF"."LOB_CONFIGURATION_ID"    AS "LOB_CONFIGURATION_ID",
    "LOB_CONFIGURATION_NOTIF"."AGENT_ID"                AS "AGENT_ID",
    "NOTIFICATION"."TEAM_LEADER_ID"                     AS "TEAM_LEADER_ID",
    "DISCREPANCY_DETECTED_NOTIF"."TIMECARD_ACTIVITY_ID" AS "TIMECARD_ACTIVITY_ID",
    "NOTIFICATION"."IS_READ"                            AS "IS_READ"
  FROM "TBL_DISCREPANCY_DETECTED_NOTIF" "DISCREPANCY_DETECTED_NOTIF"
  JOIN "TBL_NOTIFICATION" "NOTIFICATION"
  ON "NOTIFICATION".Id = "DISCREPANCY_DETECTED_NOTIF".Id
  JOIN "TBL_LOB_CONFIGURATION_NOTIF" "LOB_CONFIGURATION_NOTIF"
  ON "LOB_CONFIGURATION_NOTIF".Id = "DISCREPANCY_DETECTED_NOTIF".Id;

CREATE OR REPLACE FORCE VIEW "PULSEUSER"."DURATION_MISMATCH_NOTIF" ("ID", "TYPE", "AUX_CODE_ENTRY_NAME", "NAME", "END_TIME", "MESSAGE", "CREATED_ON", "DURATION", "LOB_CONFIGURATION_ID", "WORKED_ID", "AGENT_ID", "TIMECARD_ACTIVITY_ID", "TEAM_LEADER_ID", "IS_READ", "TIMECARD_ID")
                                                        AS
  SELECT "DURATION_MISMATCH_NOTIF"."ID"                 AS "ID",
    "NOTIFICATION"."TYPE"                               AS "TYPE",
    "DISCREPANCY_DETECTED_NOTIF"."AUX_CODE_ENTRY_NAME"  AS "AUX_CODE_ENTRY_NAME",
    "NOTIFICATION"."NAME"                               AS "NAME",
    "DURATION_MISMATCH_NOTIF"."END_TIME"                AS "END_TIME",
    "LOB_CONFIGURATION_NOTIF"."MESSAGE"                 AS "MESSAGE",
    "NOTIFICATION"."CREATED_ON"                         AS "CREATED_ON",
    "DURATION_MISMATCH_NOTIF"."DURATION"                AS "DURATION",
    "LOB_CONFIGURATION_NOTIF"."LOB_CONFIGURATION_ID"    AS "LOB_CONFIGURATION_ID",
    "LOB_CONFIGURATION_NOTIF"."WORKED_ID"               AS "WORKED_ID",
    "LOB_CONFIGURATION_NOTIF"."AGENT_ID"                AS "AGENT_ID",
    "DISCREPANCY_DETECTED_NOTIF"."TIMECARD_ACTIVITY_ID" AS "TIMECARD_ACTIVITY_ID",
    "NOTIFICATION"."TEAM_LEADER_ID"                     AS "TEAM_LEADER_ID",
    "NOTIFICATION"."IS_READ"                            AS "IS_READ",
    "LOB_CONFIGURATION_NOTIF"."TIMECARD_ID"             AS "TIMECARD_ID"
  FROM "TBL_DURATION_MISMATCH_NOTIF" "DURATION_MISMATCH_NOTIF"
  JOIN "TBL_NOTIFICATION" "NOTIFICATION"
  ON "NOTIFICATION".Id = "DURATION_MISMATCH_NOTIF".Id
  JOIN "TBL_DISCREPANCY_DETECTED_NOTIF" "DISCREPANCY_DETECTED_NOTIF"
  ON "DISCREPANCY_DETECTED_NOTIF".Id = "DURATION_MISMATCH_NOTIF".Id
  JOIN "TBL_LOB_CONFIGURATION_NOTIF" "LOB_CONFIGURATION_NOTIF"
  ON "LOB_CONFIGURATION_NOTIF".Id = "DURATION_MISMATCH_NOTIF".Id;

CREATE OR REPLACE FORCE VIEW "PULSEUSER"."DURATION_TOLERANCE_NOTIF"
("ID", "MESSAGE", "CREATED_ON", "NAME", "TYPE", "AGENT_ID", "LOB_CONFIGURATION_ID", "WORKED_ID", "LOB_CONFIGURATION_ENTRY_ID", "TEAM_LEADER_ID", "IS_READ", "TIMECARD_ID")
                                                        AS
  SELECT "THRSH_EXCEEDED_NOTIF"."ID"                    AS "ID",
    "LOB_CONFIGURATION_NOTIF"."MESSAGE"                 AS "MESSAGE",
    "NOTIFICATION"."CREATED_ON"                         AS "CREATED_ON",
    "NOTIFICATION"."NAME"                               AS "NAME",
    "NOTIFICATION"."TYPE"                               AS "TYPE",
    "LOB_CONFIGURATION_NOTIF"."AGENT_ID"                AS "AGENT_ID",
    "LOB_CONFIGURATION_NOTIF"."LOB_CONFIGURATION_ID"    AS "LOB_CONFIGURATION_ID",
    "LOB_CONFIGURATION_NOTIF"."WORKED_ID"               AS "WORKED_ID",
    "THRSH_EXCEEDED_NOTIF"."LOB_CONFIGURATION_ENTRY_ID" AS "LOB_CONFIGURATION_ENTRY_ID",
    "NOTIFICATION"."TEAM_LEADER_ID"                     AS "TEAM_LEADER_ID",
    "NOTIFICATION"."IS_READ"                            AS "IS_READ",
    "LOB_CONFIGURATION_NOTIF"."TIMECARD_ID"             AS "TIMECARD_ID"
  FROM "TBL_DURATION_TOLERANCE_NOTIF" "DURATION_TOLERANCE_NOTIF"
  JOIN "TBL_THRSH_EXCEEDED_NOTIF" "THRSH_EXCEEDED_NOTIF"
  ON "THRSH_EXCEEDED_NOTIF".Id = "DURATION_TOLERANCE_NOTIF".Id
  JOIN "TBL_LOB_CONFIGURATION_NOTIF" "LOB_CONFIGURATION_NOTIF"
  ON "LOB_CONFIGURATION_NOTIF".Id = "DURATION_TOLERANCE_NOTIF".Id
  JOIN "TBL_NOTIFICATION" "NOTIFICATION"
  ON "NOTIFICATION".Id = "DURATION_TOLERANCE_NOTIF".Id;

CREATE OR REPLACE FORCE VIEW "PULSEUSER"."INV_ACTVTY_CODE_NOTIF" ("ID", "TYPE", "NAME", "MESSAGE", "CREATED_ON", "AGENT_ID", "LOB_CONFIGURATION_ID","WORKED_ID", "LOB_CONFIGURATION_ENTRY_ID", "TEAM_LEADER_ID", "IS_READ", "TIMECARD_ID")
                                                        AS
  SELECT "THRSH_EXCEEDED_NOTIF"."ID"                    AS "ID",
    "NOTIFICATION"."TYPE"                               AS "TYPE",
    "NOTIFICATION"."NAME"                               AS "NAME",
    "LOB_CONFIGURATION_NOTIF"."MESSAGE"                 AS "MESSAGE",
    "NOTIFICATION"."CREATED_ON"                         AS "CREATED_ON",
    "LOB_CONFIGURATION_NOTIF"."AGENT_ID"                AS "AGENT_ID",
    "LOB_CONFIGURATION_NOTIF"."LOB_CONFIGURATION_ID"    AS "LOB_CONFIGURATION_ID",
    "LOB_CONFIGURATION_NOTIF"."WORKED_ID"               AS "WORKED_ID",
    "THRSH_EXCEEDED_NOTIF"."LOB_CONFIGURATION_ENTRY_ID" AS "LOB_CONFIGURATION_ENTRY_ID",
    "NOTIFICATION"."TEAM_LEADER_ID"                     AS "TEAM_LEADER_ID",
    "NOTIFICATION"."IS_READ"                            AS "IS_READ",
    "LOB_CONFIGURATION_NOTIF"."TIMECARD_ID"             AS "TIMECARD_ID"
  FROM "TBL_INV_ACTVTY_CODE_NOTIF" "INV_ACTVTY_CODE_NOTIF"
  JOIN "TBL_THRSH_EXCEEDED_NOTIF" "THRSH_EXCEEDED_NOTIF"
  ON "THRSH_EXCEEDED_NOTIF".Id = "INV_ACTVTY_CODE_NOTIF".Id
  JOIN "TBL_NOTIFICATION" "NOTIFICATION"
  ON "NOTIFICATION".Id = "INV_ACTVTY_CODE_NOTIF".Id
  JOIN "TBL_LOB_CONFIGURATION_NOTIF" "LOB_CONFIGURATION_NOTIF"
  ON "LOB_CONFIGURATION_NOTIF".Id = "INV_ACTVTY_CODE_NOTIF".Id;

CREATE OR REPLACE FORCE VIEW "PULSEUSER"."NON_BILLABLE_ACTVTY_NOTIF" ("ID", "TYPE", "AUX_CODE_ENTRY_NAME", "MESSAGE", "CREATED_ON", "NAME", "LOB_CONFIGURATION_ID", "AGENT_ID", "WORKED_ID", "TEAM_LEADER_ID", "TIMECARD_ACTIVITY_ID", "IS_READ", "TIMECARD_ID")
                                                        AS
  SELECT "DISCREPANCY_DETECTED_NOTIF"."ID"              AS "ID",
    "NOTIFICATION"."TYPE"                               AS "TYPE",
    "DISCREPANCY_DETECTED_NOTIF"."AUX_CODE_ENTRY_NAME"  AS "AUX_CODE_ENTRY_NAME",
    "LOB_CONFIGURATION_NOTIF"."MESSAGE"                 AS "MESSAGE",
    "NOTIFICATION"."CREATED_ON"                         AS "CREATED_ON",
    "NOTIFICATION"."NAME"                               AS "NAME",
    "LOB_CONFIGURATION_NOTIF"."LOB_CONFIGURATION_ID"    AS "LOB_CONFIGURATION_ID",
    "LOB_CONFIGURATION_NOTIF"."AGENT_ID"                AS "AGENT_ID",
    "LOB_CONFIGURATION_NOTIF"."WORKED_ID"               AS "WORKED_ID",
    "NOTIFICATION"."TEAM_LEADER_ID"                     AS "TEAM_LEADER_ID",
    "DISCREPANCY_DETECTED_NOTIF"."TIMECARD_ACTIVITY_ID" AS "TIMECARD_ACTIVITY_ID",
    "NOTIFICATION"."IS_READ"                            AS "IS_READ",
    "LOB_CONFIGURATION_NOTIF"."TIMECARD_ID"             AS "TIMECARD_ID"
  FROM "TBL_NON_BILLABLE_ACTVTY_NOTIF" "NON_BILLABLE_ACTVTY_NOTIF"
  JOIN "TBL_DISCREPANCY_DETECTED_NOTIF" "DISCREPANCY_DETECTED_NOTIF"
  ON "DISCREPANCY_DETECTED_NOTIF".Id = "NON_BILLABLE_ACTVTY_NOTIF".Id
  JOIN "TBL_NOTIFICATION" "NOTIFICATION"
  ON "NOTIFICATION".Id = "NON_BILLABLE_ACTVTY_NOTIF".Id
  JOIN "TBL_LOB_CONFIGURATION_NOTIF" "LOB_CONFIGURATION_NOTIF"
  ON "LOB_CONFIGURATION_NOTIF".Id = "NON_BILLABLE_ACTVTY_NOTIF".Id;


CREATE OR REPLACE FORCE VIEW "PULSEUSER"."OCCURRENCE_MISMATCH_NOTIF" ("ID", "TYPE", "AUX_CODE_ENTRY_NAME", "MESSAGE", "CREATED_ON", "NAME", "LOB_CONFIGURATION_ID", "WORKED_ID", "AGENT_ID", "TIMECARD_ACTIVITY_ID", "TEAM_LEADER_ID", "IS_READ","TIMECARD_ID")
                                                        AS
  SELECT "DISCREPANCY_DETECTED_NOTIF"."ID"              AS "ID",
    "NOTIFICATION"."TYPE"                               AS "TYPE",
    "DISCREPANCY_DETECTED_NOTIF"."AUX_CODE_ENTRY_NAME"  AS "AUX_CODE_ENTRY_NAME",
    "LOB_CONFIGURATION_NOTIF"."MESSAGE"                 AS "MESSAGE",
    "NOTIFICATION"."CREATED_ON"                         AS "CREATED_ON",
    "NOTIFICATION"."NAME"                               AS "NAME",
    "LOB_CONFIGURATION_NOTIF"."LOB_CONFIGURATION_ID"    AS "LOB_CONFIGURATION_ID",
    "LOB_CONFIGURATION_NOTIF"."WORKED_ID"               AS "WORKED_ID",
    "LOB_CONFIGURATION_NOTIF"."AGENT_ID"                AS "AGENT_ID",
    "DISCREPANCY_DETECTED_NOTIF"."TIMECARD_ACTIVITY_ID" AS "TIMECARD_ACTIVITY_ID",
    "NOTIFICATION"."TEAM_LEADER_ID"                     AS "TEAM_LEADER_ID",
    "NOTIFICATION"."IS_READ"                            AS "IS_READ",
    "LOB_CONFIGURATION_NOTIF"."TIMECARD_ID"             AS "TIMECARD_ID"
  FROM "TBL_OCCURRENCE_MISMATCH_NOTIF" "OCCURRENCE_MISMATCH_NOTIF"
  JOIN "TBL_DISCREPANCY_DETECTED_NOTIF" "DISCREPANCY_DETECTED_NOTIF"
  ON "DISCREPANCY_DETECTED_NOTIF".Id = "OCCURRENCE_MISMATCH_NOTIF".Id
  JOIN "TBL_NOTIFICATION" "NOTIFICATION"
  ON "NOTIFICATION".Id = "OCCURRENCE_MISMATCH_NOTIF".Id
  JOIN "TBL_LOB_CONFIGURATION_NOTIF" "LOB_CONFIGURATION_NOTIF"
  ON "LOB_CONFIGURATION_NOTIF".Id = "OCCURRENCE_MISMATCH_NOTIF".Id;

CREATE OR REPLACE FORCE VIEW "PULSEUSER"."OCCURRENCE_TOLERANCE_NOTIF" ("ID", "MESSAGE", "CREATED_ON", "NAME", "TYPE", "AGENT_ID", "LOB_CONFIGURATION_ID",  "WORKED_ID", "LOB_CONFIGURATION_ENTRY_ID", "TEAM_LEADER_ID", "IS_READ", "TIMECARD_ID")
                                                        AS
  SELECT "THRSH_EXCEEDED_NOTIF"."ID"                    AS "ID",
    "LOB_CONFIGURATION_NOTIF"."MESSAGE"                 AS "MESSAGE",
    "NOTIFICATION"."CREATED_ON"                         AS "CREATED_ON",
    "NOTIFICATION"."NAME"                               AS "NAME",
    "NOTIFICATION"."TYPE"                               AS "TYPE",
    "LOB_CONFIGURATION_NOTIF"."AGENT_ID"                AS "AGENT_ID",
    "LOB_CONFIGURATION_NOTIF"."LOB_CONFIGURATION_ID"    AS "LOB_CONFIGURATION_ID",
    "LOB_CONFIGURATION_NOTIF"."WORKED_ID"               AS "WORKED_ID",
    "THRSH_EXCEEDED_NOTIF"."LOB_CONFIGURATION_ENTRY_ID" AS "LOB_CONFIGURATION_ENTRY_ID",
    "NOTIFICATION"."TEAM_LEADER_ID"                     AS "TEAM_LEADER_ID",
    "NOTIFICATION"."IS_READ"                            AS "IS_READ",
    "LOB_CONFIGURATION_NOTIF"."TIMECARD_ID"             AS "TIMECARD_ID"
  FROM "TBL_OCCURRENCE_TOLERANCE_NOTIF" "OCCURRENCE_TOLERANCE_NOTIF"
  JOIN "TBL_THRSH_EXCEEDED_NOTIF" "THRSH_EXCEEDED_NOTIF"
  ON "THRSH_EXCEEDED_NOTIF".Id = "OCCURRENCE_TOLERANCE_NOTIF".Id
  JOIN "TBL_LOB_CONFIGURATION_NOTIF" "LOB_CONFIGURATION_NOTIF"
  ON "LOB_CONFIGURATION_NOTIF".Id = "OCCURRENCE_TOLERANCE_NOTIF".Id
  JOIN "TBL_NOTIFICATION" "NOTIFICATION"
  ON "NOTIFICATION".Id = "OCCURRENCE_TOLERANCE_NOTIF".Id;
CREATE OR REPLACE FORCE VIEW "PULSEUSER"."THRSH_EXCEEDED_NOTIF" ("ID", "MESSAGE", "CREATED_ON", "NAME", "TYPE", "LOB_CONFIGURATION_ID", "AGENT_ID", "TEAM_LEADER_ID", "LOB_CONFIGURATION_ENTRY_ID", "IS_READ", "WORKED_ID", "TIMECARD_ID")
                                                        AS
  SELECT "THRSH_EXCEEDED_NOTIF"."ID"                    AS "ID",
    "LOB_CONFIGURATION_NOTIF"."MESSAGE"                 AS "MESSAGE",
    "NOTIFICATION"."CREATED_ON"                         AS "CREATED_ON",
    "NOTIFICATION"."NAME"                               AS "NAME",
    "NOTIFICATION"."TYPE"                               AS "TYPE",
    "LOB_CONFIGURATION_NOTIF"."LOB_CONFIGURATION_ID"    AS "LOB_CONFIGURATION_ID",
    "LOB_CONFIGURATION_NOTIF"."AGENT_ID"                AS "AGENT_ID",
    "NOTIFICATION"."TEAM_LEADER_ID"                     AS "TEAM_LEADER_ID",
    "THRSH_EXCEEDED_NOTIF"."LOB_CONFIGURATION_ENTRY_ID" AS "LOB_CONFIGURATION_ENTRY_ID",
    "NOTIFICATION"."IS_READ"                            AS "IS_READ",
    "LOB_CONFIGURATION_NOTIF"."WORKED_ID"               AS "WORKED_ID",
    "LOB_CONFIGURATION_NOTIF"."TIMECARD_ID"             AS "TIMECARD_ID"
  FROM "TBL_THRSH_EXCEEDED_NOTIF" "THRSH_EXCEEDED_NOTIF"
  JOIN "TBL_LOB_CONFIGURATION_NOTIF" "LOB_CONFIGURATION_NOTIF"
  ON "LOB_CONFIGURATION_NOTIF".Id = "THRSH_EXCEEDED_NOTIF".Id
  JOIN "TBL_NOTIFICATION" "NOTIFICATION"
  ON "NOTIFICATION".Id = "THRSH_EXCEEDED_NOTIF".Id;

CREATE OR REPLACE FORCE VIEW "PULSEUSER"."WORK_DURATION_NOTIFICATION" ("ID", "MESSAGE", "CREATED_ON", "NAME", "TYPE", "LOB_CONFIGURATION_ID", "AGENT_ID", "CMS_ENTRY_ID", "TEAM_LEADER_ID", "LOB_CONFIGURATION_ENTRY_ID", "IS_READ")
                                                        AS
  SELECT "WORK_DURATION_NOTIFICATION"."ID"              AS "ID",
    "LOB_CONFIGURATION_NOTIF"."MESSAGE"                 AS "MESSAGE",
    "NOTIFICATION"."CREATED_ON"                         AS "CREATED_ON",
    "NOTIFICATION"."NAME"                               AS "NAME",
    "NOTIFICATION"."TYPE"                               AS "TYPE",
    "LOB_CONFIGURATION_NOTIF"."LOB_CONFIGURATION_ID"    AS "LOB_CONFIGURATION_ID",
    "LOB_CONFIGURATION_NOTIF"."AGENT_ID"                AS "AGENT_ID",
    "LOB_CONFIGURATION_NOTIF"."CMS_ENTRY_ID"            AS "CMS_ENTRY_ID",
    "NOTIFICATION"."TEAM_LEADER_ID"                     AS "TEAM_LEADER_ID",
    "THRSH_EXCEEDED_NOTIF"."LOB_CONFIGURATION_ENTRY_ID" AS "LOB_CONFIGURATION_ENTRY_ID",
    "NOTIFICATION"."IS_READ"                            AS "IS_READ"
  FROM "TBL_WORK_DURATION_NOTIFICATION" "WORK_DURATION_NOTIFICATION"
  JOIN "TBL_LOB_CONFIGURATION_NOTIF" "LOB_CONFIGURATION_NOTIF"
  ON "LOB_CONFIGURATION_NOTIF".Id = "WORK_DURATION_NOTIFICATION".Id
  JOIN "TBL_NOTIFICATION" "NOTIFICATION"
  ON "NOTIFICATION".Id = "WORK_DURATION_NOTIFICATION".Id
  JOIN "TBL_THRSH_EXCEEDED_NOTIF" "THRSH_EXCEEDED_NOTIF"
  ON "THRSH_EXCEEDED_NOTIF".Id = "WORK_DURATION_NOTIFICATION".Id;

CREATE OR REPLACE FORCE VIEW "PULSEUSER"."WORK_MODE_OCCURRENCE_NOTIF" ("ID", "MESSAGE", "CREATED_ON", "NAME", "TYPE", "LOB_CONFIGURATION_ID", "AGENT_ID", "CMS_ENTRY_ID", "TEAM_LEADER_ID", "LOB_CONFIGURATION_ENTRY_ID", "IS_READ")
                                                        AS
  SELECT "WORK_MODE_OCCURRENCE_NOTIF"."ID"              AS "ID",
    "LOB_CONFIGURATION_NOTIF"."MESSAGE"                 AS "MESSAGE",
    "NOTIFICATION"."CREATED_ON"                         AS "CREATED_ON",
    "NOTIFICATION"."NAME"                               AS "NAME",
    "NOTIFICATION"."TYPE"                               AS "TYPE",
    "LOB_CONFIGURATION_NOTIF"."LOB_CONFIGURATION_ID"    AS "LOB_CONFIGURATION_ID",
    "LOB_CONFIGURATION_NOTIF"."AGENT_ID"                AS "AGENT_ID",
    "LOB_CONFIGURATION_NOTIF"."CMS_ENTRY_ID"            AS "CMS_ENTRY_ID",
    "NOTIFICATION"."TEAM_LEADER_ID"                     AS "TEAM_LEADER_ID",
    "THRSH_EXCEEDED_NOTIF"."LOB_CONFIGURATION_ENTRY_ID" AS "LOB_CONFIGURATION_ENTRY_ID",
    "NOTIFICATION"."IS_READ"                            AS "IS_READ"
  FROM "TBL_WORK_MODE_OCCURRENCE_NOTIF" "WORK_MODE_OCCURRENCE_NOTIF"
  JOIN "TBL_LOB_CONFIGURATION_NOTIF" "LOB_CONFIGURATION_NOTIF"
  ON "LOB_CONFIGURATION_NOTIF".Id = "WORK_MODE_OCCURRENCE_NOTIF".Id
  JOIN "TBL_NOTIFICATION" "NOTIFICATION"
  ON "NOTIFICATION".Id = "WORK_MODE_OCCURRENCE_NOTIF".Id
  JOIN "TBL_THRSH_EXCEEDED_NOTIF" "THRSH_EXCEEDED_NOTIF"
  ON "THRSH_EXCEEDED_NOTIF".Id = "WORK_MODE_OCCURRENCE_NOTIF".Id;

CREATE OR REPLACE FORCE VIEW "PULSEUSER"."LOB_CONFIGURATION_NOTIF" ("ID", "NAME", "TYPE", "MESSAGE", "CREATED_ON", "AGENT_ID", "LOB_CONFIGURATION_ID", "TEAM_LEADER_ID", "CMS_ENTRY_ID", "WORKED_ID", "IS_READ", "TIMECARD_ID")
                                                     AS
  SELECT "NOTIFICATION"."ID"                         AS "ID",
    "NOTIFICATION"."NAME"                            AS "NAME",
    "NOTIFICATION"."TYPE"                            AS "TYPE",
    "LOB_CONFIGURATION_NOTIF"."MESSAGE"              AS "MESSAGE",
    "NOTIFICATION"."CREATED_ON"                      AS "CREATED_ON",
    "LOB_CONFIGURATION_NOTIF"."AGENT_ID"             AS "AGENT_ID",
    "LOB_CONFIGURATION_NOTIF"."LOB_CONFIGURATION_ID" AS "LOB_CONFIGURATION_ID",
    "NOTIFICATION"."TEAM_LEADER_ID"                  AS "TEAM_LEADER_ID",
    "LOB_CONFIGURATION_NOTIF"."CMS_ENTRY_ID"         AS "CMS_ENTRY_ID",
    "LOB_CONFIGURATION_NOTIF"."WORKED_ID"            AS "WORKED_ID",
    "NOTIFICATION"."IS_READ"                         AS "IS_READ",
    "LOB_CONFIGURATION_NOTIF"."TIMECARD_ID"          AS "TIMECARD_ID"
  FROM "TBL_LOB_CONFIGURATION_NOTIF" "LOB_CONFIGURATION_NOTIF"
  JOIN "TBL_NOTIFICATION" "NOTIFICATION"
  ON "NOTIFICATION".Id = "LOB_CONFIGURATION_NOTIF".Id;