create or replace PROCEDURE TRUTRACK.INSERT_SCHEDULE
(
vID OUT NUMBER,
vPAYROLL IN NVARCHAR2,
vSHIFT IN NUMBER,
vSTART_DATE IN DATE,
vEND_DATE IN DATE,
vSTART_TIME IN DATE,
vEND_TIME IN DATE,
vHOUR_TYPE IN NUMBER,
vREASON IN NVARCHAR2,
vAPPROVED IN VARCHAR,
vAPPROVED_BY IN NVARCHAR2,
vPLAN_SCHED_ID IN NUMBER,
vCLIENT_ID IN NUMBER

) IS
 --vID INTEGER := 1;
BEGIN

 SELECT LAST_VALUE + 1 INTO vID
 FROM TRUTRACK.SEQUENCE_CLIENT
  WHERE sequence_name ='SCHEDULE_ORION' and client_id='1';

Insert into trutrack.schedule_orion (ID,PAYROLL,SHIFT,START_DATE,END_DATE,START_TIME,END_TIME,HOUR_TYPE,REASON,APPROVED,APPROVED_BY,PLAN_SCHED_ID,CLIENT_ID) values (vID, vPAYROLL, vSHIFT, vSTART_DATE, vEND_DATE, vSTART_TIME, vEND_TIME, vHOUR_TYPE, vREASON, vAPPROVED, vAPPROVED_BY, vPLAN_SCHED_ID, vCLIENT_ID);

UPDATE TRUTRACK.SEQUENCE_CLIENT SET LAST_VALUE = LAST_VALUE+1 WHERE sequence_name ='SCHEDULE_ORION' and client_id='1';

COMMIT;

END INSERT_SCHEDULE;
/

create or replace PROCEDURE TRUTRACK.INSERT_SCHEDULE_ENTRY
(
vID OUT NUMBER,
vPAYROLL IN NVARCHAR2,
vSTART_DATE IN DATE,
vEND_DATE IN  DATE,
vCOST_POS_INDEX IN  NUMBER,
vCENTRE IN   NVARCHAR2,
vPOSITION IN NVARCHAR2,
vCURRENT_LEVEL IN    NUMBER,
vPREVIOUS_LEVEL IN   NUMBER,
vLEVEL_DATE IN  DATE,
vJOB_PERCENT IN  FLOAT,
vREASON IN   NVARCHAR2,
vAPPROVED IN NCHAR,
vAPPROVED_BY IN  NVARCHAR2,
vSTART_TIME IN  DATE,
vEND_TIME IN  DATE,
vMODIFIED_TIMESTAMP IN DATE,
vCLIENT_ID IN   NUMBER
) IS
 --vID INTEGER := 1;
BEGIN

 SELECT max(ID) + 1 INTO vID
 FROM trutrack.job_schedule_orion ;

Insert into trutrack.job_schedule_orion  (ID,PAYROLL,START_DATE,END_DATE,COST_POS_INDEX,CENTRE,POSITION,CURRENT_LEVEL,PREVIOUS_LEVEL,LEVEL_DATE,JOB_PERCENT,REASON,APPROVED,APPROVED_BY,START_TIME,END_TIME,MODIFIED_TIMESTAMP,CLIENT_ID)
values (vID,vPAYROLL,vSTART_DATE,vEND_DATE,vCOST_POS_INDEX,vCENTRE,vPOSITION,vCURRENT_LEVEL,vPREVIOUS_LEVEL,vLEVEL_DATE,vJOB_PERCENT,vREASON,vAPPROVED,vAPPROVED_BY,vSTART_TIME,vEND_TIME,vMODIFIED_TIMESTAMP,vCLIENT_ID);


COMMIT;

END INSERT_SCHEDULE_ENTRY;
/
