
package com.cybershift.wfm3.mcs10;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-31T09:23:43.630-07:00
 * Generated source version: 3.1.2
 */

@WebFault(name = "Fault", targetNamespace = "http://www.cybershift.com/wfm3/mcs10/")
public class FaultMessage extends Exception {
    
    private com.cybershift.wfm3.mcs10.Fault fault;

    public FaultMessage() {
        super();
    }
    
    public FaultMessage(String message) {
        super(message);
    }
    
    public FaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public FaultMessage(String message, com.cybershift.wfm3.mcs10.Fault fault) {
        super(message);
        this.fault = fault;
    }

    public FaultMessage(String message, com.cybershift.wfm3.mcs10.Fault fault, Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public com.cybershift.wfm3.mcs10.Fault getFaultInfo() {
        return this.fault;
    }
}
