package com.cybershift.wfm3.mcs10;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-31T09:23:43.640-07:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://www.cybershift.com/wfm3/mcs10/", name = "WFM3ServicePortType")
@XmlSeeAlso({com.cybershift.wfm3._5._3.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WFM3ServicePortType {

    @WebResult(name = "DeletedObjectCount", targetNamespace = "http://www.cybershift.com/wfm3/mcs10/", partName = "body")
    @WebMethod(action = "urn:deleteData")
    public java.math.BigInteger deleteData(
        @WebParam(partName = "body", name = "DeleteData", targetNamespace = "http://www.cybershift.com/wfm3/mcs10/")
        DeleteData body
    ) throws FaultMessage;

    @WebResult(name = "ValueObjects", targetNamespace = "http://www.cybershift.com/wfm3/mcs10/", partName = "body")
    @WebMethod(action = "urn:updateAndRetrieveData")
    public ValueObjects updateAndRetrieveData(
        @WebParam(partName = "body", name = "UpdateAndRetrieveData", targetNamespace = "http://www.cybershift.com/wfm3/mcs10/")
        UpdateAndRetrieveData body
    ) throws FaultMessage;

    @WebResult(name = "OperationResult", targetNamespace = "http://www.cybershift.com/wfm3/mcs10/", partName = "body")
    @WebMethod(action = "urn:processRequest")
    public java.lang.String processRequest(
        @WebParam(partName = "body", name = "ValueObjects", targetNamespace = "http://www.cybershift.com/wfm3/mcs10/")
        ValueObjects body
    ) throws FaultMessage;

    @WebResult(name = "ValueObjects", targetNamespace = "http://www.cybershift.com/wfm3/mcs10/", partName = "body")
    @WebMethod(action = "urn:retrieveData")
    public ValueObjects retrieveData(
        @WebParam(partName = "body", name = "RetrieveData", targetNamespace = "http://www.cybershift.com/wfm3/mcs10/")
        RetrieveData body
    ) throws FaultMessage;
}
