package com.pulse.mo;

import com.percero.framework.bl.IManifest;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;

import org.springframework.stereotype.Component;

@SuppressWarnings("rawtypes")
@Component
public class Pulse_Manifest implements IManifest
{

	private List<Class> classList = null;
	public List<Class> getClassList() {
		if (classList == null) {
			classList = new ArrayList<Class>();
			classList.add(com.pulse.mo.ActivityType.class);
classList.add(com.pulse.mo.Admin.class);
classList.add(com.pulse.mo.Notification.class);
classList.add(com.pulse.mo.Agent.class);
classList.add(com.pulse.mo.LOB.class);
classList.add(com.pulse.mo.LOBConfiguration.class);
classList.add(com.pulse.mo.LOBConfigurationNotification.class);
classList.add(com.pulse.mo.DiscrepancyDetectedNotification.class);
classList.add(com.pulse.mo.DurationMismatchNotification.class);
classList.add(com.pulse.mo.ThresholdExceededNotification.class);
classList.add(com.pulse.mo.DurationToleranceNotification.class);
classList.add(com.pulse.mo.InvalidActivityCodeNotification.class);
classList.add(com.pulse.mo.NonBillableActivityNotification.class);
classList.add(com.pulse.mo.Alert.class);
classList.add(com.pulse.mo.NotificationAlert.class);
classList.add(com.pulse.mo.NotificationFrequency.class);
classList.add(com.pulse.mo.OccurrenceMismatchNotification.class);
classList.add(com.pulse.mo.OccurrenceToleranceNotification.class);
classList.add(com.pulse.mo.PayrollDetail.class);
classList.add(com.pulse.mo.PerformanceSummary.class);
classList.add(com.pulse.mo.PulseConfiguration.class);
classList.add(com.pulse.mo.Role.class);
classList.add(com.pulse.mo.ScorecardState.class);
classList.add(com.pulse.mo.ServerCall.class);
classList.add(com.pulse.mo.ThresholdScale.class);
classList.add(com.pulse.mo.TraceLog.class);
classList.add(com.pulse.mo.WorkDurationNotification.class);
classList.add(com.pulse.mo.WorkModeOccurrenceNotification.class);
classList.add(com.pulse.mo.ActualTime.class);
classList.add(com.pulse.mo.ActualTimeEntry.class);
classList.add(com.pulse.mo.AdhocCoachingCategory.class);
classList.add(com.pulse.mo.AdhocCoachingSession.class);
classList.add(com.pulse.mo.AdhocTask.class);
classList.add(com.pulse.mo.AdhocTaskState.class);
classList.add(com.pulse.mo.AgentTime.class);
classList.add(com.pulse.mo.AgentTimeEntry.class);
classList.add(com.pulse.mo.AppAction.class);
classList.add(com.pulse.mo.Attachment.class);
classList.add(com.pulse.mo.AuxMode.class);
classList.add(com.pulse.mo.Behavior.class);
classList.add(com.pulse.mo.Client.class);
classList.add(com.pulse.mo.CoachingSession.class);
classList.add(com.pulse.mo.CoachingSessionMeasure.class);
classList.add(com.pulse.mo.CoachingSessionState.class);
classList.add(com.pulse.mo.ConnectedState.class);
classList.add(com.pulse.mo.ManagerApproval.class);
classList.add(com.pulse.mo.EmployeeAcknowledgement.class);
classList.add(com.pulse.mo.HRApproval.class);
classList.add(com.pulse.mo.SupervisorAcknowledgement.class);
classList.add(com.pulse.mo.CorrectiveAction.class);
classList.add(com.pulse.mo.CorrectiveActionState.class);
classList.add(com.pulse.mo.CorrectiveActionType.class);
classList.add(com.pulse.mo.Credential.class);
classList.add(com.pulse.mo.CVGProject.class);
classList.add(com.pulse.mo.Dashboard.class);
classList.add(com.pulse.mo.DevelopmentActivity.class);
classList.add(com.pulse.mo.Email.class);
classList.add(com.pulse.mo.EStartActivityCode.class);
classList.add(com.pulse.mo.GeneralComment.class);
classList.add(com.pulse.mo.LOBConfigurationEntry.class);
classList.add(com.pulse.mo.Observation.class);
classList.add(com.pulse.mo.TeamLeader.class);
classList.add(com.pulse.mo.PulseUser.class);
classList.add(com.pulse.mo.QualityEvaluation.class);
classList.add(com.pulse.mo.ScheduledActivityCode.class);
classList.add(com.pulse.mo.ScheduledTime.class);
classList.add(com.pulse.mo.ScheduledTimeEntry.class);
classList.add(com.pulse.mo.Scorecard.class);
classList.add(com.pulse.mo.Setting.class);
classList.add(com.pulse.mo.Site.class);
classList.add(com.pulse.mo.Supervisor.class);
classList.add(com.pulse.mo.TeamLeaderAction.class);
classList.add(com.pulse.mo.TeamLeaderImpersonation.class);
classList.add(com.pulse.mo.ThresholdGradeScale.class);
classList.add(com.pulse.mo.ThresholdLevel.class);
classList.add(com.pulse.mo.TraceEntry.class);
classList.add(com.pulse.mo.UserRole.class);
classList.add(com.pulse.mo.UserSession.class);
classList.add(com.pulse.mo.ChangesNotApprovedNotification.class);
classList.add(com.pulse.mo.CoachingNotification.class);

		}
		return classList;
	}

	private List<Object> objectList = null;
	public List<Object> getObjectList() {
		if (objectList == null) {
			objectList = new ArrayList<Object>();
			objectList.add(new com.pulse.mo.ActivityType());
objectList.add(new com.pulse.mo.Admin());
objectList.add(new com.pulse.mo.Notification());
objectList.add(new com.pulse.mo.Agent());
objectList.add(new com.pulse.mo.LOB());
objectList.add(new com.pulse.mo.LOBConfiguration());
objectList.add(new com.pulse.mo.LOBConfigurationNotification());
objectList.add(new com.pulse.mo.DiscrepancyDetectedNotification());
objectList.add(new com.pulse.mo.DurationMismatchNotification());
objectList.add(new com.pulse.mo.ThresholdExceededNotification());
objectList.add(new com.pulse.mo.DurationToleranceNotification());
objectList.add(new com.pulse.mo.InvalidActivityCodeNotification());
objectList.add(new com.pulse.mo.NonBillableActivityNotification());
objectList.add(new com.pulse.mo.Alert());
objectList.add(new com.pulse.mo.NotificationAlert());
objectList.add(new com.pulse.mo.NotificationFrequency());
objectList.add(new com.pulse.mo.OccurrenceMismatchNotification());
objectList.add(new com.pulse.mo.OccurrenceToleranceNotification());
objectList.add(new com.pulse.mo.PayrollDetail());
objectList.add(new com.pulse.mo.PerformanceSummary());
objectList.add(new com.pulse.mo.PulseConfiguration());
objectList.add(new com.pulse.mo.Role());
objectList.add(new com.pulse.mo.ScorecardState());
objectList.add(new com.pulse.mo.ServerCall());
objectList.add(new com.pulse.mo.ThresholdScale());
objectList.add(new com.pulse.mo.TraceLog());
objectList.add(new com.pulse.mo.WorkDurationNotification());
objectList.add(new com.pulse.mo.WorkModeOccurrenceNotification());
objectList.add(new com.pulse.mo.ActualTime());
objectList.add(new com.pulse.mo.ActualTimeEntry());
objectList.add(new com.pulse.mo.AdhocCoachingCategory());
objectList.add(new com.pulse.mo.AdhocCoachingSession());
objectList.add(new com.pulse.mo.AdhocTask());
objectList.add(new com.pulse.mo.AdhocTaskState());
objectList.add(new com.pulse.mo.AgentTime());
objectList.add(new com.pulse.mo.AgentTimeEntry());
objectList.add(new com.pulse.mo.AppAction());
objectList.add(new com.pulse.mo.Attachment());
objectList.add(new com.pulse.mo.AuxMode());
objectList.add(new com.pulse.mo.Behavior());
objectList.add(new com.pulse.mo.Client());
objectList.add(new com.pulse.mo.CoachingSession());
objectList.add(new com.pulse.mo.CoachingSessionMeasure());
objectList.add(new com.pulse.mo.CoachingSessionState());
objectList.add(new com.pulse.mo.ConnectedState());
objectList.add(new com.pulse.mo.ManagerApproval());
objectList.add(new com.pulse.mo.EmployeeAcknowledgement());
objectList.add(new com.pulse.mo.HRApproval());
objectList.add(new com.pulse.mo.SupervisorAcknowledgement());
objectList.add(new com.pulse.mo.CorrectiveAction());
objectList.add(new com.pulse.mo.CorrectiveActionState());
objectList.add(new com.pulse.mo.CorrectiveActionType());
objectList.add(new com.pulse.mo.Credential());
objectList.add(new com.pulse.mo.CVGProject());
objectList.add(new com.pulse.mo.Dashboard());
objectList.add(new com.pulse.mo.DevelopmentActivity());
objectList.add(new com.pulse.mo.Email());
objectList.add(new com.pulse.mo.EStartActivityCode());
objectList.add(new com.pulse.mo.GeneralComment());
objectList.add(new com.pulse.mo.LOBConfigurationEntry());
objectList.add(new com.pulse.mo.Observation());
objectList.add(new com.pulse.mo.TeamLeader());
objectList.add(new com.pulse.mo.PulseUser());
objectList.add(new com.pulse.mo.QualityEvaluation());
objectList.add(new com.pulse.mo.ScheduledActivityCode());
objectList.add(new com.pulse.mo.ScheduledTime());
objectList.add(new com.pulse.mo.ScheduledTimeEntry());
objectList.add(new com.pulse.mo.Scorecard());
objectList.add(new com.pulse.mo.Setting());
objectList.add(new com.pulse.mo.Site());
objectList.add(new com.pulse.mo.Supervisor());
objectList.add(new com.pulse.mo.TeamLeaderAction());
objectList.add(new com.pulse.mo.TeamLeaderImpersonation());
objectList.add(new com.pulse.mo.ThresholdGradeScale());
objectList.add(new com.pulse.mo.ThresholdLevel());
objectList.add(new com.pulse.mo.TraceEntry());
objectList.add(new com.pulse.mo.UserRole());
objectList.add(new com.pulse.mo.UserSession());
objectList.add(new com.pulse.mo.ChangesNotApprovedNotification());
objectList.add(new com.pulse.mo.CoachingNotification());

		}
		return objectList;
	}

	private Map<String, Class> uuidMap = null;
	public Map<String, Class> getUuidMap() {
		if (uuidMap == null) {
			uuidMap = new HashMap<String, Class>();
			uuidMap.put("59b41234-2ca6-45ab-88b2-42456627f106", com.pulse.mo.ActivityType.class);
uuidMap.put("62cc18c9-2807-4be6-be61-97b1f6b268c2", com.pulse.mo.Admin.class);
uuidMap.put("a3d97370-c3e4-41a7-adff-1f3d2de5e9f5", com.pulse.mo.Notification.class);
uuidMap.put("752f16fd-5728-4bbb-b390-ca4d18ff9611", com.pulse.mo.Agent.class);
uuidMap.put("4ae8ff49-8645-43ad-93b7-aad74f4e38bd", com.pulse.mo.LOB.class);
uuidMap.put("904a5bb1-5178-44d9-a678-ddfeff296034", com.pulse.mo.LOBConfiguration.class);
uuidMap.put("7868c62a-96c4-4a83-8794-7e22e09b8efb", com.pulse.mo.LOBConfigurationNotification.class);
uuidMap.put("d1d94a03-2dd1-4ab2-9cf3-131942d7bfe1", com.pulse.mo.DiscrepancyDetectedNotification.class);
uuidMap.put("2ad3a1c4-4e97-4455-aacb-ae2fd72213c8", com.pulse.mo.DurationMismatchNotification.class);
uuidMap.put("dc974643-7744-4788-a925-d99ae78b979f", com.pulse.mo.ThresholdExceededNotification.class);
uuidMap.put("689f38b4-8a8b-4f8e-9141-281a3789da3f", com.pulse.mo.DurationToleranceNotification.class);
uuidMap.put("9d5d3372-7039-42df-8af7-9f31b6de0483", com.pulse.mo.InvalidActivityCodeNotification.class);
uuidMap.put("6134140c-b5c8-4888-9a05-fcde78129046", com.pulse.mo.NonBillableActivityNotification.class);
uuidMap.put("1d182b93-6a6c-44f6-8a3c-948333f13549", com.pulse.mo.Alert.class);
uuidMap.put("9cd40ca0-ccbc-4c8c-ae44-aa2b53bf9712", com.pulse.mo.NotificationAlert.class);
uuidMap.put("9040f7f4-5999-4926-942f-417314f6d03d", com.pulse.mo.NotificationFrequency.class);
uuidMap.put("f807b30e-65a8-4169-9eb9-7ba8cebe07dc", com.pulse.mo.OccurrenceMismatchNotification.class);
uuidMap.put("1380193f-7c94-4aba-bde7-84d1a9780b1f", com.pulse.mo.OccurrenceToleranceNotification.class);
uuidMap.put("db7add20-0103-4e56-a835-8ef2b45154b6", com.pulse.mo.PayrollDetail.class);
uuidMap.put("17226d90-de89-4bc9-b4a8-00db1dd45387", com.pulse.mo.PerformanceSummary.class);
uuidMap.put("8653df6a-bca2-47ca-94b8-8e20a1f0072d", com.pulse.mo.PulseConfiguration.class);
uuidMap.put("9eafae72-37b3-47ec-87e7-4891b2417cfd", com.pulse.mo.Role.class);
uuidMap.put("43727338-75f2-45ab-ad9b-b4069aaeb39c", com.pulse.mo.ScorecardState.class);
uuidMap.put("71658445-7f04-490d-beb2-0d4cc69e5c32", com.pulse.mo.ServerCall.class);
uuidMap.put("a2bff6ce-c309-45ad-8ccc-4e953e2cde8f", com.pulse.mo.ThresholdScale.class);
uuidMap.put("3a67a1a4-5973-4863-87c0-fc647de50ff4", com.pulse.mo.TraceLog.class);
uuidMap.put("9c2e2340-0885-45a8-860a-6cbcfd8f391f", com.pulse.mo.WorkDurationNotification.class);
uuidMap.put("8b3b0cb2-e9e7-4083-878f-99cf617b8aaa", com.pulse.mo.WorkModeOccurrenceNotification.class);
uuidMap.put("0725d0ea-1747-49d1-8a48-b76383d5f08e", com.pulse.mo.ActualTime.class);
uuidMap.put("4c8c9b14-6b6b-4699-8c28-913751b15785", com.pulse.mo.ActualTimeEntry.class);
uuidMap.put("f9cdc749-2e2a-4cfb-a687-62ac0bb95268", com.pulse.mo.AdhocCoachingCategory.class);
uuidMap.put("06bd57c8-a05d-4642-9193-1d24f78589a6", com.pulse.mo.AdhocCoachingSession.class);
uuidMap.put("a3d74377-afd4-4394-adc4-11e5f2c48f16", com.pulse.mo.AdhocTask.class);
uuidMap.put("a9eff6f0-2996-4d3e-a672-adfacf1b3b3c", com.pulse.mo.AdhocTaskState.class);
uuidMap.put("0a9e7051-0bd5-41b2-9a41-aee6cb3d4c9c", com.pulse.mo.AgentTime.class);
uuidMap.put("227bb0f2-4b49-4b79-910c-b2e60c177396", com.pulse.mo.AgentTimeEntry.class);
uuidMap.put("cc5f9816-dcac-4f1f-9074-61b77c9897a0", com.pulse.mo.AppAction.class);
uuidMap.put("e7fc513f-6c83-4448-9074-4a6abce08eb9", com.pulse.mo.Attachment.class);
uuidMap.put("dbd598b4-dc38-4b03-aeff-86d7b06d777a", com.pulse.mo.AuxMode.class);
uuidMap.put("fcab62f8-9b8c-470e-a830-35a02bdb9a42", com.pulse.mo.Behavior.class);
uuidMap.put("efec6703-6416-4fed-bb8c-20d276bc3b8e", com.pulse.mo.Client.class);
uuidMap.put("b5c6d4a7-15aa-4ffd-a11d-4833de5c6791", com.pulse.mo.CoachingSession.class);
uuidMap.put("b9be69df-b0a4-4121-9941-295c88c12752", com.pulse.mo.CoachingSessionMeasure.class);
uuidMap.put("fa20cd34-6083-4168-8470-8e78e1d30481", com.pulse.mo.CoachingSessionState.class);
uuidMap.put("5dc280e7-05f7-4b4b-aec6-f9429d94999a", com.pulse.mo.ConnectedState.class);
uuidMap.put("10c482f8-5363-4a9f-90b4-455f42ed39f5", com.pulse.mo.ManagerApproval.class);
uuidMap.put("1bd6a5dc-8167-4f82-9d42-62dfad6f42b0", com.pulse.mo.EmployeeAcknowledgement.class);
uuidMap.put("a4f37742-04fb-431e-896b-8fcce4402ba1", com.pulse.mo.HRApproval.class);
uuidMap.put("077682c0-2277-4e83-8ac6-83a98b60b2f1", com.pulse.mo.SupervisorAcknowledgement.class);
uuidMap.put("ef9ae7a9-02d8-46e1-977e-d9b4086baf09", com.pulse.mo.CorrectiveAction.class);
uuidMap.put("e602ee40-1709-41c1-8dcb-8a4cd8f63c3e", com.pulse.mo.CorrectiveActionState.class);
uuidMap.put("50e95d25-8ea9-4596-964f-33aa8a7f47ec", com.pulse.mo.CorrectiveActionType.class);
uuidMap.put("2f3d242c-eded-4c01-86b6-5270ef78c556", com.pulse.mo.Credential.class);
uuidMap.put("2b562f31-510a-421e-9049-886cab0b496a", com.pulse.mo.CVGProject.class);
uuidMap.put("f0cc17b6-086d-4459-960f-20e359079ba9", com.pulse.mo.Dashboard.class);
uuidMap.put("5d9e1297-1ae2-4606-bdc2-3667b1eda521", com.pulse.mo.DevelopmentActivity.class);
uuidMap.put("6fd29ebc-782d-4dc2-959d-849e8a605cf9", com.pulse.mo.Email.class);
uuidMap.put("4a1c05bc-375f-4c51-a142-4f0256b77795", com.pulse.mo.EStartActivityCode.class);
uuidMap.put("250a4e17-68e5-4af6-a1f0-cfe7a421c9e7", com.pulse.mo.GeneralComment.class);
uuidMap.put("e0e6a23a-77a4-4208-a0c4-ad660d756eb7", com.pulse.mo.LOBConfigurationEntry.class);
uuidMap.put("2822b84b-7d8e-4d90-befb-e6e0b9b3e6a2", com.pulse.mo.Observation.class);
uuidMap.put("bb0213e8-e69f-45e9-a581-c50fa4ec9857", com.pulse.mo.TeamLeader.class);
uuidMap.put("a95710ec-cfb3-43c2-8b93-52ad8368f7f4", com.pulse.mo.PulseUser.class);
uuidMap.put("67f17784-ded3-40f4-ad45-e04dfd3a91b7", com.pulse.mo.QualityEvaluation.class);
uuidMap.put("4762c949-f841-4295-a791-f1e7e37e0473", com.pulse.mo.ScheduledActivityCode.class);
uuidMap.put("2dc73309-fb64-4fb7-9f48-51042d489472", com.pulse.mo.ScheduledTime.class);
uuidMap.put("3fe36d8b-5f73-4a45-97a3-aca7e0f9b2c8", com.pulse.mo.ScheduledTimeEntry.class);
uuidMap.put("c47a3aef-0256-491b-97d4-60134e3c6021", com.pulse.mo.Scorecard.class);
uuidMap.put("544510e5-4ab4-482e-9469-5d194ea64e50", com.pulse.mo.Setting.class);
uuidMap.put("541e59c4-d2c1-4ff0-943c-8eb19f7e35dc", com.pulse.mo.Site.class);
uuidMap.put("8f2e1fea-c71c-4b47-adc1-23cb43e8c13f", com.pulse.mo.Supervisor.class);
uuidMap.put("fcedce9b-6d37-4131-9a25-20c8df92b874", com.pulse.mo.TeamLeaderAction.class);
uuidMap.put("7e8ab0c8-7bba-44fb-a89d-a7579094512c", com.pulse.mo.TeamLeaderImpersonation.class);
uuidMap.put("7ebbba10-80e8-4c08-a4cf-9ea4c2c83de6", com.pulse.mo.ThresholdGradeScale.class);
uuidMap.put("cd502eaf-910c-4a46-bb2e-2ac1a7dbcc4d", com.pulse.mo.ThresholdLevel.class);
uuidMap.put("24f9b2e1-80c7-4f56-81ab-676845f0e589", com.pulse.mo.TraceEntry.class);
uuidMap.put("2a720d8d-fdec-4836-8a8f-861da7b8f1ec", com.pulse.mo.UserRole.class);
uuidMap.put("e28f86a7-e663-45bb-8f8d-bebdb254d0c3", com.pulse.mo.UserSession.class);
uuidMap.put("b4b62912-1553-4ce0-82c4-40e3c5ba5826", com.pulse.mo.ChangesNotApprovedNotification.class);
uuidMap.put("e910c10d-602e-4d79-b037-555253dd791a", com.pulse.mo.CoachingNotification.class);

		}
		return uuidMap;
	}

}